#define CONTROLLER 1
#define TURN 2

#define FRONT_ROTATIONAL 1,5
#define BACK_ROTATIONAL 1,4
#define	FRONT_LEFT_MOTOR 1,1
#define FRONT_RIGHT_MOTOR 1,2
#define BACK_LEFT_MOTOR 1,3
#define BACK_RIGHT_MOTOR 1,6

#define FRONT_POT 1,2
#define BACK_POT 1,1
